{{- $root := . -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "streams-app-cleanup-job.fullname" . }}
  labels:
    app: {{ template "streams-app-cleanup-job.name" . }}
    chart: {{ template "streams-app-cleanup-job.chart" . }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  ttlSecondsAfterFinished: 30
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- if .Values.awsRole }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.awsRole }}
    {{- end }}
      labels:
        app: {{ template "streams-app-cleanup-job.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "streams-app-cleanup-job.name" . }}-container
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ENV_PREFIX
              value: {{ .Values.configurationEnvPrefix }}_
            - name: "{{ .Values.configurationEnvPrefix }}_STREAMS_CONFIG"
              value: "{{- range $key, $value := .Values.streams.config }}{{ $key }}={{ $value }},{{- end }}"
            - name: "{{ .Values.configurationEnvPrefix }}_BROKERS"
              value: {{ .Values.streams.brokers | quote }}
            - name: "{{ .Values.configurationEnvPrefix }}_SCHEMA_REGISTRY_URL"
              value: {{ .Values.streams.schemaRegistryUrl | quote }}
            {{- if hasKey .Values.streams "productive" }}
            - name: "{{ .Values.configurationEnvPrefix }}_PRODUCTIVE"
              value: {{ .Values.streams.productive | quote }}
            {{- end }}
            {{- if hasKey .Values "debug" }}
            - name: "{{ .Values.configurationEnvPrefix }}_DEBUG"
              value: {{ .Values.debug | quote }}
            {{- end }}
            - name: "{{ .Values.configurationEnvPrefix }}_CLEAN_UP"
              value: "true"
            {{- if hasKey .Values.streams "deleteOutput" }}
            - name: "{{ .Values.configurationEnvPrefix }}_DELETE_OUTPUT"
              value: {{ .Value.streams.deleteOutput | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "inputTopics" }}
            - name: "{{ .Values.configurationEnvPrefix }}_INPUT_TOPICS"
              value: {{ .Values.streams.inputTopics | join "," | quote }}
                    {{- end }}
                    {{- if hasKey .Values.streams "outputTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_OUTPUT_TOPIC"
              value: {{ .Values.streams.outputTopic | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "errorTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_ERROR_TOPIC"
              value: {{ .Values.streams.errorTopic | quote }}
            {{- end }}
            {{- range $key, $value := .Values.commandLine }}
            - name: "{{ $root.Values.configurationEnvPrefix }}_{{ $key }}"
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}