apiVersion: v1
entries:
  rclone-copy:
  - apiVersion: v1
    created: 2020-11-03T18:18:33.404117553+01:00
    description: A helm chart for rclone copy on Kubernetes.
    digest: 76bfa8090f35f661898da7748513d4f454a75ab26507bc01f35b617762048d0f
    name: rclone-copy
    urls:
    - rclone-copy/rclone-copy-1.0.0.tgz
    version: 1.0.0
  streams-app:
  - apiVersion: v1
    created: 2020-11-03T18:18:33.408514312+01:00
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: 45b8846fcc805aadaa6e51a7a317bcca2f073f4c4b78118da452dbb21f52e719
    name: streams-app
    urls:
    - streams-app/streams-app-0.1.0.tgz
    version: 0.1.0
  streams-app-cleanup-job:
  - apiVersion: v1
    created: 2020-11-03T18:18:33.409586744+01:00
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: e5c7f03175a4c3000073d1471f9b03738c59b9c7029810835ef72db11b04f85c
    name: streams-app-cleanup-job
    urls:
    - streams-app-cleanup-job/streams-app-cleanup-job-0.1.0.tgz
    version: 0.1.0
generated: 2020-11-03T18:18:33.402640903+01:00
