apiVersion: v1
entries:
  rclone-copy:
  - apiVersion: v1
    created: 2020-11-09T11:36:38.846844462+01:00
    description: A helm chart for rclone copy on Kubernetes.
    digest: 76bfa8090f35f661898da7748513d4f454a75ab26507bc01f35b617762048d0f
    name: rclone-copy
    urls:
    - rclone-copy/rclone-copy-1.0.0.tgz
    version: 1.0.0
  streams-app:
  - apiVersion: v1
    created: 2020-11-09T11:36:38.852845481+01:00
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: fdfdd7bfc75a9d6d2b499540ad05e188b8fa6c01129d0c09825e1a7b9df078ef
    name: streams-app
    urls:
    - streams-app/streams-app-0.1.0.tgz
    version: 0.1.0
  streams-app-cleanup-job:
  - apiVersion: v1
    created: 2020-11-09T11:36:38.854245802+01:00
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: e85f195ee64906abeb891b8250ad3a3ab81278bc70e5eed2edb46f87fda1452f
    name: streams-app-cleanup-job
    urls:
    - streams-app-cleanup-job/streams-app-cleanup-job-0.1.0.tgz
    version: 0.1.0
generated: 2020-11-09T11:36:38.845039868+01:00
