apiVersion: v1
entries:
  rclone-copy:
  - apiVersion: v1
    created: "2020-04-09T12:46:51.157938546+02:00"
    description: A helm chart for rclone copy on Kubernetes.
    digest: 40ce12fa2377bf99cfe30207ae1891af24de9b3406fe79686100e38046042376
    name: rclone-copy
    urls:
    - rclone-copy/rclone-copy-1.0.0.tgz
    version: 1.0.0
  streams-app:
  - apiVersion: v1
    created: "2020-04-09T12:46:51.160830555+02:00"
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: 3398b4afe28474cf716d092442cf7506efe8224129fba798f41c6cbaa91806f6
    name: streams-app
    urls:
    - streams-app/streams-app-0.1.0.tgz
    version: 0.1.0
  streams-app-cleanup-job:
  - apiVersion: v1
    created: "2020-04-09T12:46:51.161507576+02:00"
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: 1f2dc49ab1f582fea83c5c04ce8650baff95b36f031cca027089c2d73936b968
    name: streams-app-cleanup-job
    urls:
    - streams-app-cleanup-job/streams-app-cleanup-job-0.1.0.tgz
    version: 0.1.0
generated: "2020-04-09T12:46:51.157535206+02:00"
