apiVersion: v1
entries:
  rclone-copy:
  - apiVersion: v1
    created: "2019-12-18T14:49:42.170002+01:00"
    description: A helm chart for rclone copy on Kubernetes.
    digest: 40ce12fa2377bf99cfe30207ae1891af24de9b3406fe79686100e38046042376
    name: rclone-copy
    urls:
    - rclone-copy/rclone-copy-1.0.0.tgz
    version: 1.0.0
  streams-app:
  - apiVersion: v1
    created: "2019-12-18T14:49:42.1724+01:00"
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: ddc002a099c68a65e51d6a77724430b29f1f59ddb6a5788f717d2c1c8af34e93
    name: streams-app
    urls:
    - streams-app/streams-app-0.1.0.tgz
    version: 0.1.0
  streams-app-cleanup-job:
  - apiVersion: v1
    created: "2019-12-18T14:49:42.174101+01:00"
    description: A helm chart for deploying a kafka streams application based on the
      bakdata KafkaStreamsApplication template.
    digest: 833014e5065f2e36934513673bfc78fb03fc7e34db96d1333440abe0f58045ac
    name: streams-app-cleanup-job
    urls:
    - streams-app-cleanup-job/streams-app-cleanup-job-0.1.0.tgz
    version: 0.1.0
generated: "2019-12-18T14:49:42.168781+01:00"
