apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "streams-app-job.fullname" . }}
  labels:
    app: {{ template "streams-app-job.name" . }}
    chart: {{ template "streams-app-job.chart" . }}
    release: {{ .Release.Name }}
spec:
  ttlSecondsAfterFinished: 30
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
    {{- if .Values.awsRole }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.awsRole }}
    {{- end }}
      labels:
        app: {{ template "streams-app-job.name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ template "streams-app-job.name" . }}-container
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ENV_PREFIX
              value: {{ .Values.configurationEnvPrefix }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
