nameOverride: bakdata-streams-app-job

replicaCount: 1

image: streamsApp
imageTag: latest
imagePullPolicy: Always

configurationEnvPrefix: "APP"

streams:
#  brokers: "test:9092"
#  schemaRegistryUrl: "url:1234"
  config:
#    max.poll.records: 500
#    Note that YAML may convert large integers to scientific notation. Use Strings to avoid this.
#    max.request.size: "1000000"
#  inputTopics:
#  - input
#  - input2
#  outputTopic: output
#  errorTopic: error
#  productive: true
  deleteOutput: false

#commandLine:
#  MY_CLI_PARAM: "foo-bar"
#
#debug: false
#
env:
#  MY_ENV_VARIABLE: foo-bar
#
#secrets:
#  MY_SECRET: fo-bar

# tolerations:
#   - key: "foo"
#     operator: "Exists"
#     effect: "NoSchedule"
#   - key: "bar"
#     operator: "Exists"
#     effect: "NoSchedule"

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 2G

javaOptions:
  maxRAMPercentage: 75
  others: []
#   - "-XX:MinRAMPercentage=50.0"
