{{- $root := . -}}

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "streams-app.fullname" . }}
  labels:
    app: {{ template "streams-app.name" . }}
    chart: {{ template "streams-app.chart" . }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "streams-app.name" $ }}
      release: {{ .Release.Name }}
  template:
    metadata:
    {{- if or (or .Values.awsRole .Values.prometheus.jmx.enabled) .Values.annotations }}
      annotations:
      {{- if .Values.awsRole }}
        iam.amazonaws.com/role: {{ .Values.awsRole }}
      {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.prometheus.jmx.port | quote }}
      {{- end }}
      {{- range $key, $value := .Values.annotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        app: {{ template "streams-app.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      affinity:
        podAntiAffinity:
        {{- if .Values.requirePodAntiAffinity }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ template "streams-app.name" . }}
            topologyKey: "kubernetes.io/hostname"
        {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - {{ template "streams-app.name" . }}
        {{- end }}
      containers:
        - name: {{ template "streams-app.name" . }}-container
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ENV_PREFIX
              value: {{ .Values.configurationEnvPrefix }}_
          {{- range $key, $value := .Values.streams.config }}
            - name: {{ printf "STREAMS_%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.prometheus.jmx.enabled }}
            - name: KAFKA_JMX_PORT
              value: "{{ .Values.jmx.port }}"
          {{- end }}
            - name: "{{ .Values.configurationEnvPrefix }}_BROKERS"
              value: {{ .Values.streams.brokers | quote }}
            - name: "{{ .Values.configurationEnvPrefix }}_SCHEMA_REGISTRY_URL"
              value: {{ .Values.streams.schemaRegistryUrl | quote }}
          {{- if hasKey .Values.streams "productive" }}
            - name: "{{ .Values.configurationEnvPrefix }}_PRODUCTIVE"
              value: {{ .Values.streams.productive | quote }}
          {{- end }}
          {{- if hasKey .Values "debug" }}
            - name: "{{ .Values.configurationEnvPrefix }}_DEBUG"
              value: {{ .Values.debug | quote }}
          {{- end }}
          {{- if hasKey .Values.streams "inputTopics" }}
            - name: "{{ .Values.configurationEnvPrefix }}_INPUT_TOPICS"
              value: {{ .Values.streams.inputTopics | join "," | quote }}
          {{- end }}
          {{- if hasKey .Values.streams "outputTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_OUTPUT_TOPIC"
              value: {{ .Values.streams.outputTopic | quote }}
          {{- end }}
          {{- if hasKey .Values.streams "errorTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_ERROR_TOPIC"
              value: {{ .Values.streams.errorTopic | quote }}
          {{- end }}
          {{- range $key, $value := .Values.secrets }}
            - name: "{{ $key }}"
              valueFrom:
                secretKeyRef:
                  name: {{ template "streams-app.fullname" $ }}
                  key: "{{ $key }}"
          {{- end }}
          {{- range $key, $value := .Values.commandLine }}
            - name: "{{ $root.Values.configurationEnvPrefix }}_{{ $key }}"
              value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
            - name: JAVA_TOOL_OPTIONS
              value: "-Dcom.sun.management.jmxremote.port={{ .Values.jmx.port }} -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
        {{- if .Values.log4jConfig }}
          volumeMounts:
            - name: {{ template "streams-app.name" . }}-log4j-config-volume
              mountPath: app/resources/log4j.properties
              subPath: log4j.properties
        {{- end }}
        {{- if .Values.prometheus.jmx.enabled }}
          ports:
            - containerPort: {{ .Values.jmx.port }}
              name: jmx
        {{- end }}
      {{- if .Values.prometheus.jmx.enabled }}
        - name: prometheus-jmx-exporter
          image: "{{ .Values.prometheus.jmx.image }}:{{ .Values.prometheus.jmx.imageTag }}"
          command:
            - java
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+UseCGroupMemoryLimitForHeap
            - -XX:MaxRAMFraction=1
            - -XshowSettings:vm
            - -jar
            - jmx_prometheus_httpserver.jar
            - {{ .Values.prometheus.jmx.port | quote }}
            - /etc/jmx-streams-app/jmx-kafka-streams-app-prometheus.yml
          ports:
            - containerPort: {{ .Values.prometheus.jmx.port }}
          resources:
{{ toYaml .Values.prometheus.jmx.resources | indent 12 }}
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-streams-app
      {{- end }}
      {{- if or (.Values.prometheus.jmx.enabled) (.Values.log4jConfig) }}
      volumes:
        {{- if .Values.prometheus.jmx.enabled }}
        - name: jmx-config
          configMap:
            name: {{ template "streams-app.name" . }}-jmx-configmap
        {{- end }}
        {{ if .Values.log4jConfig }}
        - name: {{ template "streams-app.name" . }}-log4j-config-volume
          configMap:
            name: {{ template "streams-app.name" . }}-log4j-configmap
            items:
              - key: log4j.properties
                path: log4j.properties
        {{- end }}
      {{- end }}
